n_rrt_nodes: 500

min_bounds: [-10, -10, -1.5]
max_bounds: [10, 10, 1.5]

near_radius_rrt: 1.5

delta_distance_rrt: 1.0

robot_radius: 1.0

n_fail_iterations_rrt: 1000

# arrays with size proportional to number of cameras
camera_info_k: [343.15907310693535, 0.0, 320.5, 0.0, 343.15907310693535, 240.5, 0.0, 0.0, 1.0]
camera_resolution: [640, 480, 2.0]
discretization_interval: [300,200,0.2]

# frame ids
base_frame_id: A01/base_link
world_frame_id: world
cam_frame_id: [A01/base_link/camera_front_optical]

# time intervals
time_interval_pose_graph: 3.0
time_interval_replan: 2

# gains
c_gain: [1.2, 0.5, 2.0]

# lookahead point distance
lookahead_path_len: 2.0

verbose: true
